CREATE DATABASE FilmsDB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE FilmsDB;

CREATE TABLE SYSTEMUSER (
  userName VARCHAR(24),
  userPassword VARCHAR(254),
  userEmail VARCHAR(254) NOT NULL UNIQUE,
  CONSTRAINT PK_SYSTEMUSER PRIMARY KEY (userName)
);

CREATE TABLE PASSWORDRESETCODE(
  userEmail VARCHAR(254) NOT NULL,
  resetCode INT,
  CONSTRAINT PK_PASSWORDRESETCODE PRIMARY KEY (userEmail),
  CONSTRAINT FK_PASSWORDRESETCODE FOREIGN KEY (userEmail) REFERENCES SYSTEMUSER (userEmail)
);

CREATE TABLE FILM (
  filmId BIGINT NOT NULL AUTO_INCREMENT,
  filmName VARCHAR(254) NOT NULL UNIQUE,
  filmDuration INT,
  memoryAddress VARCHAR(254),
  CONSTRAINT PK_FILM PRIMARY KEY (filmId)
);

CREATE TABLE ViewedFilm (
  userName VARCHAR(24),
  filmId BIGINT NOT NULL,
  viewDate DATE,
  rating INT,
  CONSTRAINT PK_ViewedFilm PRIMARY KEY (filmId),
  CONSTRAINT FK_ViewedFilm FOREIGN KEY (filmId) REFERENCES FILM (filmId)
);

INSERT INTO SYSTEMUSER (userName, userPassword, userEmail) VALUES ('Ignacio', 'Root1224', 'ignaciocabrera1224@gmail.com');